# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
	"iPhone 6s",
	"iPhone 6s Plus",
	"iPhone 5s",
	"iPhone 4s",
	"iPad Retina",
	"iPad Pro"
])

languages([
  "ru"
])

# The name of the scheme which contains the UI Tests
scheme "Civilbudget"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

clear_previous_screenshots true

# Choose which project/workspace to use
# project "../Civilbudget.xcodeproj"
# workspace "./Project.xcworkspace"

stop_after_first_error true
skip_open_summary true

# For more information about all available options run
# snapshot --help
