language: objective-c
xcode_project: PromiseKit.xcodeproj
xcode_scheme: [PMKiOS, PMKOSX]
xcode_sdk: [iphonesimulator9.3, macosx10.11]
osx_image: xcode8

install:
  - "gem install travis-xcodebuild"
  - "TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3 carthage bootstrap --platform Mac,iOS --no-use-binaries"

script:
  - travis-xcodebuild

matrix:
  exclude:
    - xcode_scheme: PMKOSX
      xcode_sdk: iphonesimulator9.3
    - xcode_scheme: PMKiOS
      xcode_sdk: macosx10.11

after_success:
  - bash <(curl -s https://codecov.io/bash)
